# Name: Daniel Ivan Lewis
# Date: 10/19/18
# ISTA 116 Section C
# Lab Assignment 06
# Collaborator(s): None

download.file("http://www.openintro.org/stat/data/bdims.RData", destfile = "bdims.RData")
load("bdims.RData")

# Question 1:
fdims <- subset(bdims, bdims$sex == 0)
hist(fdims$hgt, probability = TRUE, ylim = c(0.00, 0.08))
# Answer: Based off of the histogram generated from the female hight column, the distribution does appear to be close to a normal distribution. If there were a normal distribution layed on top of the curve it would follow the same shape of the histogram created. 

# Quesiton 2:
x <- seq(range(fdims$hgt)[1], range(fdims$hgt)[2], by = 0.1)

# Question 3:
y <- dnorm(x, mean(fdims$hgt), sd(fdims$hgt))

# Question 4:
lines(x, y, col = 'green')
# Answer: If the data is normally distributed, the line that is genrated should fall close to the centers of each bin as a normal curve. As far as the visual created, it does fall close to a normal distribution. Although there are some center bins that are underneath the curve, for the most part the histogram follows a close resemblence to a normal curve. 

# Question 5:
qqnorm(fdims$hgt)
qqline(fdims$hgt)
# Answer: The qqnorm plot should resemble the line that appears when qqline is called. As far as the visual generated, most of the points created by qqnorm fall close to the center of qqline, which would mean that the data follows a normal distribution. There are some variances at the ends of the line that fall off, but other than those small points, the line does seem to resemble a close to normal distribution. 

# Question 6:
r.sample <- rnorm(length(fdims$hgt), mean(fdims$hgt), sd(fdims$hgt))
qqnorm(r.sample)
qqline(r.sample)
# Answer: The normality plot created from the random sample should be close to similar than the previous qq plot generated with the actual values. This is due to the fact that the standard deviation and the mean of both the sample and the actual data are the same. Just like the previous qq plot, we are also able to see that the random sample is close to the line genreated from qqline, with a few deviations towards the end of the lines, however, for the most part, it does follow a normal distribution.

# Question 7:
qqnormsim(fdims$hgt)
# Answer: According to the plots generated by qqnormsim, it looks as though most of the 'sim' simulation plots are close to the qqline generated, therefore it gives us more visual representations to assume verify that the data passed in is close to a normal distribution.

# Question 8:
qqnormsim(fdims$age)
hist(fdims$age, probability = TRUE)
# Answer for Age variable: At first I attempted to check the dataset by using the qqnormsim function to save some time, however, it seems as though most of the simulations do seem to follow a normal distribution. Yet, the actual data does not, there is a lot of variation. I then used the hist() function, which shows that there is a huge right skew, which would not qualify the data set as a normal distribution. 

qqnormsim(fdims$wgt)
hist(fdims$wgt, probability = TRUE)
# Answer: For the weight variable, it seems as though it would be a bit closer to a normal distribution than when looking at the age variable. Yet, it still seems to show a right skew big enough to disqualify it form being a normal distribution.

# Question 9:
hgt.abv.182.prob <- pnorm(182, mean(fdims$hgt), sd(fdims$hgt), lower.tail = FALSE)
actual.abv.182 <- length(subset(fdims, fdims$hgt > 182)$hgt)/ length(fdims$hgt)
# Answer: From the values genreated above. It can be seen that the actual probability of a woman being above 182 cm is 0.003846154, which is right in par with the pnorm probability of 0.004434387 that was given. Therefore it can be seen that the estimate was very close to the actua value from the actual data set, as to be expected. Close but not exact. 

# Question 10:
hgt.90th.per <- qnorm(.9, mean(fdims$hgt), sd(fdims$hgt))
actual.90th.per <- sort(fdims$hgt)[(length(fdims$hgt)/100)*90]
# Answer: From the values genreated above. It can be seen that the percentile created by the qnorm function gives us a value of 173.2596 as the 90th percentile. Which is close to the actual 90th percentile of 174. This is to be expected since the data used is close to a normal distribution. 