#Name: Daniel Lewis
# Date:12/5/18
# ISTA 116
#Collaborator: Fil Ruiz

download.file("http://www.openintro.org/stat/data/mlb11.RData", destfile = "mlb11.RData")
load("mlb11.RData")

# Question 1:
plot(mlb11$at_bats, mlb11$runs)
# From the data generated with the code above, it does look like there is some sort of association with as the number of at bats increase, the number of runs increase as well. 

# Question 2: 
corr_coefficient = cor(mlb11$at_bats,mlb11$runs)
# From the correlation coefficient genreated with the code above, we get a value of .610627, this tells us that there is some sort of positive association between both of the variables observed. 

# Question 3:
plot_ss(x=mlb11$at_bats, y=mlb11$runs)
# Attempt 1: Sum of Squares:  183252.9
# Attempt 2: Sum of Squares:  169443.4
# Attempt 3: Sum of Squares:  194737.6
# From the three atempts above, it looks as through the smalles sum of squares that we were able to get was 169443.4

# Question 4: 
lm1=lm(at_bats ~runs, data=mlb11)
lm(at_bats ~runs, data=mlb11)
# Intercept: 5113.3510 Runs: 0.5913  
# It seems as though the line of best fit that I had created was at a much steeper slope than the actual equation provided by the lm function. Whereass the line created by the lm function increases at a lower slope.

# Question 5: 
summary(lm1)
# In order to get the variability in runs explained by at bats, we need to look at Pr(>|t|), 2e-16
  
# Question 6:
plot(lm1)
# The line that is created through this plot does seem to meet all requirements. this is seen by the consitency of the residuals and the qqplot generated by the code above.

# Question 7:
lm2= lm(homeruns~runs, data=mlb11)
lm2
#equation of regression line is y =1.835 x=415.239

# Question 8:
plot(lm2)