# Name: Daniel Ivan Lewis
# Date: 11/16/18
# ISTA 116 Section C
# Lab Assignment 12
# Collaborator(s): None

download.file("http://www.openintro.org/stat/data/nc.RData", destfile = "nc.RData")
load("nc.RData")

# Question #1
nonsmoker <- by(nc$weight, nc$habit, mean)[1]
smoker <- by(nc$weight, nc$habit, mean)[2]
# Answer: From the data generated above, we can see that the average weight of babies at birth from mothers who are smokers = 6.82873, while the average weight of babies at birth from mothers who are non smokers = 7.144273.

# Question #2
by(nc$weight, nc$habit, length)
# Answer: From the by function, we can see that the distribution of smokers and non smokers do meet the required criteria for Hypothesis testing. We can see that nonsmokers equal 873 observations out of the total of 999 observations. This results in 126 observations being smokers. However, we do have enough information to conduct a hypothesis test. 

# Question #3
# Null Hypothesis: Average weight of babies from nonsmoking mothers is equal to the average weight of babies from smoking mothers, Smoking average baby weight = Non Smoking average baby weight
# Alternate Hypothesis: Average weight of babies from nonsmoking mothers is not equal to the average weight of babies from smoking mothers, Smoking average baby weight != Non Smoking average baby weight.

# Question #4
t.test(nc$weight~nc$habit)
# Answer: From the data generated above with the t.test function. We can see that there is a significance difference between the average weight of babies at birth from smoker and nonsmoker mothers. In this case, since the p value is significantly smaller than .05, we can reject the null hypothesis, which concludes that there is a significant difference between both.

# Question #5
# Answer: As far as the data generated above, we get a 95% confidence intreval of (0.05151165, 0.57957328). Since the true difference is 0.8 lbs and it is not within the confidence intreval given by the t.test() function, the data given is not consistent with the true difference, a lower p cutoff would be needed.

# Question #6
t.test(nc$weeks)
# Answer: From the data generated above, we can see that the confidence intreval is consistent with the true length of 38.5 since the true lenght is within the intreval given. 

# Question #7
t.test(nc$weeks, conf.level = 0.9)
# Answer: With the confidence level set to 90% our true lenght of weeks is not within the confidence intreval, therefore the data is not consistent with the true lenght. The reason it is no longer within the confidence intreval is because as the confidence intreval results in a smaller range as the confidence level decreases. 

# Question #8
data <- na.omit(nc)
mature <- by(data$gained, data$mature, mean)[1]
younger <- by(data$gained, data$mature, mean)[2]
t.test(data$gained~data$mature)
# Answer: Null hypothesis - Average weight gained by mature mothers = average weight gained by younger mothers. Alternate hypothesis - Average weight gained by mature mothers != average weight gained by younger mothers. From the p value generated with the t.test information, we can see that the test statistic comes out to 0.397, in this case, since it is higher than a p value of 0.05, we fail to reject the null hypothesis. This is to be expected as the average weight gain for mature mothers is approx. 29.8 while the average weight gained for younger mothers is 30.9, which is very close to each other. 

# Question #9
mature.mean <- by(nc$mage, nc$mature, mean)[1]
mature.sd <- by(nc$mage, nc$mature, sd)[1]
mature.cutoff <- qnorm(.975, mature.mean, mature.sd, lower.tail = FALSE)
younger.mean <- by(nc$mage, nc$mature, mean)[2]
younger.sd <- by(nc$mage, nc$mature, sd)[2]
younger.cutoff <- qnorm(.975, younger.mean, younger.sd, lower.tail = FALSE)
# From the data generated above, we can see that the cutoff point for mature would be approx. 32.42 and the cutoff point for younger would be 15.58. This is generated by using the qnorm function and passing in a .975 percentage, this is because this would mean that the confidence level would be at 95% with a .05% p value. The mean and standard dev of both the mature and younger are used to calculate each respecting variables cutoff value.

# Question #10
# Null hypothesis: The average weight of a baby at birth from white mothers = The average weight of a baby at birth for non white mothers. Alternate hypothesis: The average weight of a baby at birth from white mothers != to the average weight of a baby at birth for non white mothers.
length(subset(nc$whitemom, nc$whitemom == "not white"))
length(subset(nc$whitemom, nc$whitemom == "white"))
# The test does meet the conditions as there is enough information to run a hypothesis test. 
t.test(nc$weight~nc$whitemom)
# According to the t.test function, we reject the null hypothesis, since the t test value is less than a p value of 0.05. This means that from the confidence intreval given from the t.test, none of the values within the confidence intreval equal to 0, which would be the case if there was no difference between the average weight of babies from white mothers than non white mothers. 
